steps:
- name: 'gcr.io/triggermesh/mkdocs:latest'
  args: ['mkdocs', 'build']
- name: 'debian'
  args: ['ls', '/workspace/site']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/www:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/www:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/www:$REVISION_ID']
images: ['gcr.io/$PROJECT_ID/www']
