site_name: TriggerMesh
repo_url: https://github.com/triggermesh/docs
nav:
    - Home: index.md
    - Guides:
      - 'Getting Started': guides/gettingstarted.md
      - 'Secrets': guides/secrets.md
    - Client: 
      - 'Installation': 'tm/install.md'
      - 'Configuration': 'tm/configuration.md'
      - 'Usage': 'tm/usage.md'
    - Cloud: https://cloud.triggermesh.io
    - About: about.md
theme:
  name: mkdocs
